import json

from dotenv import load_dotenv
from google import genai


load_dotenv()

client = genai.Client()


def create_note_chunks(segments, max_chars=6000):
    """
    Split transcript segments into chunks for note generation.

    Each chunk preserves:
    - transcript text
    - timestamp
    - duration
    - original segment ID

    A transcript segment is never split between chunks.
    """

    chunks = []

    current_chunk = []
    current_chars = 0

    for index, segment in enumerate(segments):

        segment_with_id = {
            "id": index,
            "text": segment["text"],
            "start": segment["start"],
            "duration": segment["duration"],
        }

        segment_chars = len(segment["text"])

        if (
            current_chunk
            and current_chars + segment_chars > max_chars
        ):
            chunks.append(current_chunk)

            current_chunk = []
            current_chars = 0

        current_chunk.append(segment_with_id)
        current_chars += segment_chars

    if current_chunk:
        chunks.append(current_chunk)

    return chunks


def generate_chunk_notes(chunk):
    """
    Generate structured study notes for one transcript chunk.

    The timestamp is taken from the original transcript
    rather than generated by Gemini.
    """

    if not chunk:
        raise ValueError("Chunk cannot be empty")

    transcript_text = "\n".join(
        segment["text"]
        for segment in chunk
    )

    timestamp = chunk[0]["start"]

    prompt = f"""
You are creating study notes from a section of an
educational YouTube video.

Create concise and useful study notes from the transcript below.

Rules:
- Use only information present in the transcript.
- Do not invent facts or add outside information.
- Identify the main topic discussed in this section.
- Extract the most important information.
- Write concise bullet points.
- Preserve important technical terms.
- Do not repeat unnecessary information.
- Do not include conversational filler.
- Return ONLY valid JSON.
- Do not wrap the JSON in Markdown code fences.

Return exactly this structure:

{{
  "title": "string",
  "points": [
    "string"
  ]
}}

Transcript:

{transcript_text}
"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    if not response.text:
        raise ValueError(
            "Gemini returned an empty note response"
        )

    response_text = response.text.strip()

    if response_text.startswith("```json"):
        response_text = response_text[7:]

    elif response_text.startswith("```"):
        response_text = response_text[3:]

    if response_text.endswith("```"):
        response_text = response_text[:-3]

    response_text = response_text.strip()

    try:
        notes = json.loads(response_text)

    except json.JSONDecodeError as error:
        raise ValueError(
            "Gemini returned invalid JSON"
        ) from error

    if "title" not in notes:
        raise ValueError(
            "Notes are missing required field: title"
        )

    if "points" not in notes:
        raise ValueError(
            "Notes are missing required field: points"
        )

    if not isinstance(notes["title"], str):
        raise ValueError(
            "Note title must be a string"
        )

    if not isinstance(notes["points"], list):
        raise ValueError(
            "Note points must be a list"
        )

    if not notes["title"].strip():
        raise ValueError(
            "Note title cannot be empty"
        )

    if len(notes["points"]) == 0:
        raise ValueError(
            "Note points cannot be empty"
        )

    for point in notes["points"]:
        if not isinstance(point, str):
            raise ValueError(
                "Each note point must be a string"
            )

    # Timestamp is deliberately assigned by our backend.
    notes["timestamp"] = timestamp

    return notes